require:
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  SuggestExtensions: false

Metrics/MethodLength:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/PerceivedComplexity:
  Max: 8

Metrics/AbcSize:
  Max: 17

Metrics/ClassLength:
  Max: 100
